version: "3.8"

services:
  backend:
    image: "${COMPOSE_PROJECT_NAME}/${project_dirname}-backend:latest"
    restart: unless-stopped
    environment:
      REACT_APP_DATA_PARENT_DIR: "/mnt/data/"
    networks:
      - net
    ports:
      - 20021:4567
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/rnd/rnd/product/anpr/anpr-demographic-page/asset:/mnt/data:ro
    # cpuset: "0,2"
    logging:
      options:
        max-size: "1m"
        max-file: "5000"
    command: "npm start"

  frontend:
    image: "${COMPOSE_PROJECT_NAME}/${project_dirname}-frontend:latest"
    restart: unless-stopped
    environment:
      # REACT_APP_MQTT_SERVER: "ws://172.17.0.216:8080/"
      # REACT_APP_MQTT_DATA_TOPIC: "offloader/COM143/01/data"
      # REACT_APP_BACKEND_FILE_SERVER: "http://172.17.11.1:4567/"
      REACT_APP_MQTT_SERVER: "ws://${DOCKER_GATEWAY_HOST:-localhost}:8080/"
      REACT_APP_MQTT_DATA_TOPIC: "offloader/GLM-OUT/02/data"
      REACT_APP_BACKEND_FILE_SERVER: "http://${DOCKER_GATEWAY_HOST:-localhost}:20021/"
    networks:
      - net
    ports:
      - 20020:3000
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    # cpuset: "0,2"
    logging:
      options:
        max-size: "1m"
        max-file: "5000"
    command: "npm start"

networks:
  net:

