version: "3.8"

services:
  backend:
    image: recogine/recocloud:backend-v0.1.0-deploy
    restart: unless-stopped
    environment:
      REACT_APP_DATA_PARENT_DIR: "/mnt/anpr/"
    networks:
      - net
    ports:
      - 4567:4567
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/anpr:/mnt/anpr:ro
      - ./backend/index.js:/root/index.js:ro
    # cpuset: "0,2"
    logging:
      options:
        max-size: "1m"
        max-file: "5000"
    command: "npm start"

  frontend:
    image: recogine/recocloud:frontend-v0.1.0-deploy
    restart: unless-stopped
    environment:
      # REACT_APP_MQTT_SERVER: "ws://172.17.0.216:8080/"
      # REACT_APP_MQTT_DATA_TOPIC: "offloader/COM143/01/data"
      # REACT_APP_BACKEND_FILE_SERVER: "http://172.17.11.1:4567/"
      REACT_APP_MQTT_SERVER: "ws://${DOCKER_GATEWAY_HOST:-localhost}:8080/"
      REACT_APP_MQTT_DATA_TOPIC: "offloader/GLM-OUT/02/data"
      REACT_APP_BACKEND_FILE_SERVER: "http://${DOCKER_GATEWAY_HOST:-localhost}:4567/"
    networks:
      - net
    ports:
      - 3000:3000
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    # cpuset: "0,2"
    logging:
      options:
        max-size: "1m"
        max-file: "5000"
    command: "npm start"

networks:
  net:

